spring.application.name=posts-service


server.port=9010

spring.datasource.url=jdbc:postgresql://localhost:5432/postdb
spring.datasource.username=postgres
spring.datasource.password=akhilesh@3632
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=localhost
spring.data.redis.port=6379




